### ISSUE TITLE
[Crash]: Crash when interacting with redstone

### ISSUE THREAD

**Issue by ghost** [MCTeamPotato/Opotato#1]
### Mod Loader

Forge 36.2.39

### Minecraft Version

1.16.5

### Mod Version

1.2.0

### Notes

Note: Alternate Current malfunction. The problem is solved through the deactivation of the corresponding mixin. The problem is not solved even removing RoadRunner.

1. Run Minecraft.
2. Create a world.
3. Place redstone materials together with redstone dust (will not work well).
4. Trigger the redstone dust.
5. Game crashes.

### Crash Report

[crash-2023-03-18_21.41.03-server.txt](https://github.com/MCTeamPotato/Opotato/files/11009957/crash-2023-03-18_21.41.03-server.txt)
[crash-2023-03-18_21.50.22-server.txt](https://github.com/MCTeamPotato/Opotato/files/11009959/crash-2023-03-18_21.50.22-server.txt)

**Comment by Kasualix** [comment]
plan to rework the alternatecurrent port
thanks to your report

**Comment by Kasualix** [comment]
hopefully fixed in 1.5.0
reopen this if crash still occurs.

**Comment by Kasualix** [comment]
Oh, completely not complicated. What's related to Gui things is the Smooth Menu feature, and I will simply disable this feature when konkrete is installed.

**Comment by Kasualix** [comment]
And I would not recommend use ModernFix and Lightspeed directly together.
They do some similar patches and may cause negative optimization.
I'm working on the best way to mix their mixins recently.
