### ISSUE TITLE
[Featrue Request] Customizable Ars Nouveau's Dungeon Loot Table.

### ISSUE THREAD

**Issue by wasdspace** [MCTeamPotato/Opotato#4]
这段时间在用 Emendatus Enigmatica，发现 Ars 的魔源宝石一直在地牢宝箱里生成，找了很久也没找到禁止刷出的方法（包括 KubeJS。如果有，望不吝赐教）。
原因似乎是 Ars 将它的 Dungeon Loot Table 硬编码了：
https://github.com/EnigmaticaModpacks/Enigmatica6/issues/3815

https://github.com/baileyholl/Ars-Nouveau/blob/ef274855dc9efc336139d2ffe7b9cd8e47235eda/src/main/java/com/hollingsworth/arsnouveau/api/loot/LootTables.java#L35

https://github.com/baileyholl/Ars-Nouveau/blob/b3df4715c7da988f733858ea8355134ee45bc69d/src/main/java/com/hollingsworth/arsnouveau/common/datagen/DungeonLootGenerator.java

能否将其变为可配置？或者简单粗暴地让其可禁用，重新注入战利品表对整合包制作者来说应该也不算难事。

**Comment by Kasualix** [comment]
噢，你来的真是时候，我正打算更新

**Comment by Kasualix** [comment]
只要禁魔源宝石就行了吗？其它战利品要不要？

**Comment by wasdspace** [comment]
只需禁宝石就可以了吧，不必增加工作量
