### ISSUE TITLE
如何禁用Modern UI的调整？

### ISSUE THREAD

**Issue by Dr-WeiAL** [MCTeamPotato/Opotato#5]
加了该模组后界面尺寸就只能是很大或者很小的了，还是比较习惯中等的
![image](https://user-images.githubusercontent.com/47446553/236381028-33245577-f514-4ee0-a6c9-4f46c10c74e9.png)
![image](https://user-images.githubusercontent.com/47446553/236381037-3ea3aaeb-a5e8-47df-a0d3-41a7d8c4037d.png)

不加该模组时自动界面尺寸是这样
![image](https://user-images.githubusercontent.com/47446553/236381344-4918771a-641a-4f5c-862b-a66675529525.png)

**Comment by Kasualix** [comment]
为什么要用自动呢

**Comment by Kasualix** [comment]
mixin.opotato.modernui=false

**Comment by Dr-WeiAL** [comment]
> 为什么要用自动呢，我觉得自动真的好蠢

因为只有自动才能变成这个中等尺寸，手动改没反应(

**Comment by Kasualix** [comment]
另外可能有些误解，本模组没有对MUI进行任何调整，只是让原版的界面尺寸算法保持为原来的，不让MUI改原版的界面尺寸算法

**Comment by Dr-WeiAL** [comment]
> 另外可能有些误解，本模组没有对MUI进行任何调整，只是让原版的界面尺寸算法保持为原来的，不让MUI改原版的界面尺寸算法

确实，我记得我加MUI的原因就是原版不能搞成中等尺寸，加了之后就能改成中等尺寸了

**Comment by Kasualix** [comment]
你这儿有装铷吗？

**Comment by Dr-WeiAL** [comment]
> 你这儿有装铷吗？

试过了，装不装铷都一样不能改成中等尺寸，也就是1x和2x尺寸是一样的小尺寸，3x和4x是一样的大尺寸
装了MUI之后界面尺寸只剩1x 2x 3x，1x和2x是一样的小尺寸，3x是中等尺寸
我这边屏幕是1920x1080 100%缩放，窗口化全屏

**Comment by Kasualix** [comment]
算了，看不透，这mixin我还是删了得了
