### ISSUE TITLE
[1.16.5]被爆头时导致崩溃

### ISSUE THREAD

**Issue by XiFengXF** [MCTeamPotato/Opotato#7]
![QQ截图20230617153707](https://github.com/MCTeamPotato/Opotato/assets/97110012/86b1100b-7c2f-45cf-92dc-ccad5306e062)
[crash-2023-06-17_14.07.49-server.txt](https://github.com/MCTeamPotato/Opotato/files/11778247/crash-2023-06-17_14.07.49-server.txt)

**Comment by Kasualix** [comment]
你的错误报告，not found

**Comment by Kasualix** [comment]
https://pastebin.com/

**Comment by XiFengXF** [comment]
刚重新编辑了

**Comment by XiFengXF** [comment]
仅在该版本会出现问题，回退上个版本则不会出现

**Comment by Kasualix** [comment]
fixed in dev, but currently be busy with testing other optimization contents so won't update till it's done.
